# Chapter-03/system-info.yml

- name: Collect System Information
  hosts: centos2
  become: true
  vars:
    report_admin_email: admin@lab.local
  tasks:
    - name: Generate System Report
      include_role: 
        name: system-report
